# Generated by Django 6.0 on 2025-12-25 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='staff.room')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
                'db_table': 'key_management',
            },
        ),
        migrations.CreateModel(
            name='LaundryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=20, unique=True)),
                ('item_count', models.PositiveIntegerField()),
                ('item_list', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_proctor', 'Pending Proctor Approval'), ('approved_by_proctor', 'Approved by Proctor'), ('verified_by_security', 'Verified by Security'), ('rejected', 'Rejected'), ('taken_out', 'Taken Out')], default='pending_proctor', max_length=30)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_laundry_forms', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_forms', to='accounts.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_laundry_forms', to='accounts.security')),
            ],
            options={
                'verbose_name': 'Laundry Form',
                'verbose_name_plural': 'Laundry Forms',
                'db_table': 'laundry_forms',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True)),
                ('issue_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_proctor', 'Pending Proctor Approval'), ('approved_by_proctor', 'Approved by Proctor'), ('assigned_to_staff', 'Assigned to Staff'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_proctor', max_length=30)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to='accounts.staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='staff.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'db_table': 'maintenance_requests',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_code', models.CharField(max_length=20, unique=True)),
                ('violation_type', models.CharField(choices=[('noise', 'Noise'), ('damage', 'Damage'), ('curfew', 'Curfew Violation'), ('smoking', 'Smoking'), ('visitor', 'Visitor Violation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('consequences', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties_assigned', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'db_table': 'penalties',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('expected_check_out', models.DateField(blank=True, null=True)),
                ('actual_check_out', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'db_table': 'room_assignments',
            },
        ),
    ]
